//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Full.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Patient()
        {
            this.Tbl_VisitTime = new HashSet<Tbl_VisitTime>();
        }
    
        public int ID { get; set; }
        public string Name_Family { get; set; }
        public string Tell { get; set; }
        public string Adrs { get; set; }
        public string MeliCode { get; set; }
        public string NCodePat { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string LoginCode { get; set; }
        public string LoginName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_VisitTime> Tbl_VisitTime { get; set; }
    }
}
