//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Full.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VisitTime
    {
        public int ID { get; set; }
        public Nullable<int> PatID { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<int> SecID { get; set; }
        public Nullable<int> ServID { get; set; }
        public string Time_Date { get; set; }
        public string VTime { get; set; }
        public string LoginName { get; set; }
        public string LoginCode { get; set; }
    
        public virtual Tbl_Doctors Tbl_Doctors { get; set; }
        public virtual Tbl_Patient Tbl_Patient { get; set; }
        public virtual Tbl_Section Tbl_Section { get; set; }
        public virtual Tbl_Services Tbl_Services { get; set; }
    }
}
