//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Full.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string Name_Family { get; set; }
        public string Name_Family_Pat { get; set; }
        public string title { get; set; }
        public string title_Serv { get; set; }
        public int ID { get; set; }
    }
}
