//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Full.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Visit_Time_Full
    {
        public string Name_Family { get; set; }
        public string Tell { get; set; }
        public string Ncode { get; set; }
        public string Name_Family_Pat { get; set; }
        public string Tell_Pat { get; set; }
        public string MeliCode_Pat { get; set; }
        public string NCodePat { get; set; }
        public string LoginCode { get; set; }
        public string LoginName { get; set; }
        public string title { get; set; }
        public string title_Serv { get; set; }
        public int ID { get; set; }
        public string Time_Date { get; set; }
        public string VTime { get; set; }
    }
}
